name: IRS Shell Build

on:
  workflow_dispatch:

  push:
    branches: 
      - main
    paths:
      - irs_shell/** # The path to your custom package
      - Dockerfile       # Assuming your Dockerfile is in the root
      - .github/workflows/lab-shell-humble.yml

  pull_request:
    branches: 
      - main
    paths:
      - irs_shell/**
      - Dockerfile
      - .github/workflows/lab-shell-humble.yml

env:
  REGISTRY: ghcr.io
  OWNER: hugh-uc
  IMAGE_NAME: irs_2025_01

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        # The GITHUB_TOKEN has permission to publish to GHCR for the repo it originated from.
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: . # This path should be the root of your repository
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:humble
